In [1]:
import pandas as pd
import os

1. Extract bed from genepred by slopping and ajusting coordinates

*Get minimum intron length*

2. halLiftover

3. Adjustment of halLiftover

4. Extract sequences and MSA

In [2]:
bed = pd.read_csv("/users/genomics/cpapadopoulos/ORFs_Marta/candidateORF.slopped.adjusted.bed", sep="\t", header=None)
bed

,0,1,2,3,4,5,6,7,8,9,10,11
0,chr10,116325011,116379358,ENST00000333254.4:10:+|11|1679:232:1009|canoni...,0,+,116325011,116379358,0,8,"79,86,117,166,102,103,88,36,","0,291,15722,17024,32368,32824,53411,54311,"
1,chr10,116324485,116324527,ENST00000333254.4:10:+|4|1679:39:81|uORF|TTG,0,+,116324485,116324527,0,1,"42,","0,"
2,chr10,122697732,122699790,ENST00000329446.5:10:-|3|1088:57:1065|canonica...,0,-,122697732,122699790,0,3,"756,76,176,","0,1604,1882,"
3,chr10,30629667,30629718,ENST00000375318.4:10:-|2|811:45:96|ouORF|ATG,0,-,30629667,30629718,0,1,"51,","0,"
4,chr10,30611954,30629705,ENST00000375318.4:10:-|3|811:58:643|canonical|ATG,0,-,30611954,30629705,0,5,"70,79,159,164,113,","0,867,14150,14822,17638,"
...,...,...,...,...,...,...,...,...,...,...,...,...
424,chrX,8170031,8170643,ENST00000317103.5:X:-|16|815:308:728|canonical...,0,-,8170031,8170643,0,2,"318,102,","0,510,"
425,chrX,8791310,8800171,ENST00000543214.1:X:-|4|1544:137:1136|canonica...,0,-,8791310,8800171,0,8,"69,99,343,115,32,121,129,91,","0,2347,3767,4957,6839,7048,7655,8770,"
426,chrX,89922085,89922811,ENST00000561129.2:X:+|7|928:131:857|canonical|ATG,0,+,89922085,89922811,0,1,"726,","0,"
427,chrY,2786988,2787603,ENST00000383070.2:Y:-|5|828:80:695|canonical|ATG,0,-,2786988,2787603,0,1,"615,","0,"
428,chrY,9467000,9468816,ENST00000423647.6:Y:+|2|1171:47:932|canonical|ATG,0,+,9467000,9468816,0,5,"486,78,112,146,63,","0,1093,1299,1512,1753,"

In [ ]:
blockSizes = bed[[10]]
blockStarts = bed[[11]]

for index,row in blockSizes.iterrows():
    sepBlockSizes = blockSizes.iloc[index].str.split(',', expand=True)
    sepBlockStarts = blockStarts.iloc[index].str.split(',', expand=True)
    print(sepBlockSizes)

     0   1    2    3    4    5   6   7 8
10  79  86  117  166  102  103  88  36

TypeError: cannot unpack non-iterable int object